import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

GMAIL_SENDER_EMAIL = os.environ.get("GMAIL_SENDER_EMAIL")
GMAIL_APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD")
ADMIN_EMAIL = os.environ.get("PHOEBE_EMAIL")


def send_report_email(
    to_email: str,
    to_name: str,
    org_name: str,
    overall_score: float,
    maturity_stage: str,
    risk_band: str,
    report_text: str,
    is_admin: bool = False,
):
    """Send report email to client or admin."""

    subject = (
        f"[CereViva] NeuroSafety Report — {org_name}"
        if is_admin
        else f"Your CereViva NeuroSafety™ Assessment Report — {org_name}"
    )

    # Convert report text to basic HTML
    report_html = report_text.replace("\n", "<br>").replace("# ", "<h2>").replace("## ", "<h3>")

    if is_admin:
        intro = f"""
        <p>A new assessment has been completed.</p>
        <p><strong>Client:</strong> {to_name}<br>
        <strong>Organisation:</strong> {org_name}<br>
        <strong>Overall Score:</strong> {overall_score}/5<br>
        <strong>Maturity Stage:</strong> {maturity_stage}<br>
        <strong>Risk Band:</strong> {risk_band}</p>
        <hr>
        <p>Full AI-generated report below:</p>
        """
    else:
        intro = f"""
        <p>Dear {to_name},</p>
        <p>Thank you for completing the CereViva NeuroSafety™ Assessment.
        Your personalised report is ready.</p>
        <p><strong>Overall Score:</strong> {overall_score}/5<br>
        <strong>Maturity Stage:</strong> {maturity_stage}<br>
        <strong>Risk Band:</strong> {risk_band}</p>
        <hr>
        """

    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px;">
        <div style="background: #2B4C8F; padding: 20px; border-radius: 10px 10px 0 0;">
            <h1 style="color: white; margin: 0; font-size: 22px;">CereViva NeuroSafety™</h1>
            <p style="color: rgba(255,255,255,0.8); margin: 4px 0 0;">Assessment Report</p>
        </div>
        <div style="background: white; padding: 30px; border: 1px solid #eee; border-radius: 0 0 10px 10px;">
            {intro}
            <div style="margin-top: 20px; line-height: 1.7; color: #333;">
                {report_html}
            </div>
            <hr style="margin-top: 30px;">
            <p style="font-size: 12px; color: #999;">
                This report was generated by CereViva NeuroSafety™ AI System.<br>
                For questions, contact us at {GMAIL_SENDER_EMAIL}
            </p>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"CereViva NeuroSafety™ <{GMAIL_SENDER_EMAIL}>"
    msg["To"] = to_email
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_SENDER_EMAIL, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_SENDER_EMAIL, to_email, msg.as_string())


def send_report_to_all(
    client_name: str,
    client_email: str,
    org_name: str,
    overall_score: float,
    maturity_stage: str,
    risk_band: str,
    report_text: str,
):
    """Send report to both client and admin."""

    # Send to client
    send_report_email(
        to_email=client_email,
        to_name=client_name,
        org_name=org_name,
        overall_score=overall_score,
        maturity_stage=maturity_stage,
        risk_band=risk_band,
        report_text=report_text,
        is_admin=False,
    )

    # Send to admin
    if ADMIN_EMAIL:
        send_report_email(
            to_email=ADMIN_EMAIL,
            to_name=client_name,
            org_name=org_name,
            overall_score=overall_score,
            maturity_stage=maturity_stage,
            risk_band=risk_band,
            report_text=report_text,
            is_admin=True,
        )
