import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, To, From

SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY")
SENDER_EMAIL = os.environ.get("SENDER_EMAIL", "info@cereviva.com")
ADMIN_EMAIL = os.environ.get("PHOEBE_EMAIL")


def build_html(intro: str, report_text: str) -> str:
    report_html = ""
    for line in report_text.split("\n"):
        line = line.strip()
        if line.startswith("# "):
            report_html += f"<h2 style='color:#2B4C8F;margin-top:24px'>{line[2:]}</h2>"
        elif line.startswith("## "):
            report_html += f"<h3 style='color:#1a3a6b;margin-top:18px'>{line[3:]}</h3>"
        elif line.startswith("- "):
            report_html += f"<li style='margin-bottom:6px'>{line[2:]}</li>"
        elif line == "":
            report_html += "<br>"
        else:
            report_html += f"<p style='margin:6px 0'>{line}</p>"

    return f"""
    <html>
    <body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px;background:#f5f7fc;">
        <div style="background:#2B4C8F;padding:24px;border-radius:12px 12px 0 0;">
            <h1 style="color:white;margin:0;font-size:22px;">CereViva NeuroSafety™</h1>
            <p style="color:rgba(255,255,255,0.8);margin:4px 0 0;font-size:13px;">Assessment Report</p>
        </div>
        <div style="background:white;padding:32px;border:1px solid #eee;border-radius:0 0 12px 12px;">
            {intro}
            <div style="margin-top:24px;line-height:1.8;color:#333;">
                {report_html}
            </div>
            <hr style="margin-top:32px;border:none;border-top:1px solid #eee;">
            <p style="font-size:12px;color:#999;margin-top:16px;">
                This report was generated by CereViva NeuroSafety™ AI System.<br>
                For questions, contact us at {SENDER_EMAIL}
            </p>
        </div>
    </body>
    </html>
    """


def send_report_email(
    to_email: str,
    to_name: str,
    org_name: str,
    overall_score: float,
    maturity_stage: str,
    risk_band: str,
    report_text: str,
    is_admin: bool = False,
):
    subject = (
        f"[CereViva] New Assessment Completed — {org_name}"
        if is_admin
        else f"Your CereViva NeuroSafety™ Assessment Report — {org_name}"
    )

    if is_admin:
        intro = f"""
        <p style="color:#333">A new assessment has been completed.</p>
        <div style="background:#f0f4ff;border-radius:10px;padding:16px;margin:16px 0;">
            <p style="margin:4px 0"><strong>Client:</strong> {to_name}</p>
            <p style="margin:4px 0"><strong>Organisation:</strong> {org_name}</p>
            <p style="margin:4px 0"><strong>Overall Score:</strong> {overall_score}/5</p>
            <p style="margin:4px 0"><strong>Maturity Stage:</strong> {maturity_stage}</p>
            <p style="margin:4px 0"><strong>Risk Band:</strong> {risk_band}</p>
        </div>
        <hr style="border:none;border-top:1px solid #eee;">
        <p style="color:#333"><strong>Full AI Report:</strong></p>
        """
    else:
        intro = f"""
        <p style="color:#333">Dear {to_name},</p>
        <p style="color:#333">Thank you for completing the CereViva NeuroSafety™ Assessment.
        Your personalised report is ready.</p>
        <div style="background:#f0f4ff;border-radius:10px;padding:16px;margin:16px 0;">
            <p style="margin:4px 0"><strong>Overall Score:</strong> {overall_score}/5</p>
            <p style="margin:4px 0"><strong>Maturity Stage:</strong> {maturity_stage}</p>
            <p style="margin:4px 0"><strong>Risk Band:</strong> {risk_band}</p>
        </div>
        <hr style="border:none;border-top:1px solid #eee;">
        """

    html_content = build_html(intro, report_text)

    message = Mail(
        from_email=From(SENDER_EMAIL, "CereViva NeuroSafety™"),
        to_emails=To(to_email, to_name),
        subject=subject,
        html_content=html_content,
    )

    sg = SendGridAPIClient(SENDGRID_API_KEY)
    sg.send(message)


def send_report_to_all(
    client_name: str,
    client_email: str,
    org_name: str,
    overall_score: float,
    maturity_stage: str,
    risk_band: str,
    report_text: str,
):
    # Send to client
    try:
        send_report_email(
            to_email=client_email,
            to_name=client_name,
            org_name=org_name,
            overall_score=overall_score,
            maturity_stage=maturity_stage,
            risk_band=risk_band,
            report_text=report_text,
            is_admin=False,
        )
        print(f" Report sent to client: {client_email}")
    except Exception as e:
        print(f" Failed to send to client: {e}")

    # Send to admin
    if ADMIN_EMAIL:
        try:
            send_report_email(
                to_email=ADMIN_EMAIL,
                to_name=client_name,
                org_name=org_name,
                overall_score=overall_score,
                maturity_stage=maturity_stage,
                risk_band=risk_band,
                report_text=report_text,
                is_admin=True,
            )
            print(f" Report sent to admin: {ADMIN_EMAIL}")
        except Exception as e:
            print(f" Failed to send to admin: {e}")
